// Code generated by go-swagger; DO NOT EDIT.

package chapter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingapi/models"
)

// ChapterBuyOKCode is the HTTP code returned for type ChapterBuyOK
const ChapterBuyOKCode int = 200

/*ChapterBuyOK 章节详情

swagger:response chapterBuyOK
*/
type ChapterBuyOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20016 `json:"body,omitempty"`
}

// NewChapterBuyOK creates ChapterBuyOK with default headers values
func NewChapterBuyOK() *ChapterBuyOK {
	return &ChapterBuyOK{}
}

// WithPayload adds the payload to the chapter buy o k response
func (o *ChapterBuyOK) WithPayload(payload *models.InlineResponse20016) *ChapterBuyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the chapter buy o k response
func (o *ChapterBuyOK) SetPayload(payload *models.InlineResponse20016) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChapterBuyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*ChapterBuyDefault error

swagger:response chapterBuyDefault
*/
type ChapterBuyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewChapterBuyDefault creates ChapterBuyDefault with default headers values
func NewChapterBuyDefault(code int) *ChapterBuyDefault {
	if code <= 0 {
		code = 500
	}

	return &ChapterBuyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the chapter buy default response
func (o *ChapterBuyDefault) WithStatusCode(code int) *ChapterBuyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the chapter buy default response
func (o *ChapterBuyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the chapter buy default response
func (o *ChapterBuyDefault) WithPayload(payload *models.Error) *ChapterBuyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the chapter buy default response
func (o *ChapterBuyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ChapterBuyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
