// Code generated by go-swagger; DO NOT EDIT.

package recommend

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RecommendHandlerFunc turns a function with the right signature into a recommend handler
type RecommendHandlerFunc func(RecommendParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RecommendHandlerFunc) Handle(params RecommendParams) middleware.Responder {
	return fn(params)
}

// RecommendHandler interface for that can handle valid recommend params
type RecommendHandler interface {
	Handle(RecommendParams) middleware.Responder
}

// NewRecommend creates a new http.Handler for the recommend operation
func NewRecommend(ctx *middleware.Context, handler RecommendHandler) *Recommend {
	return &Recommend{Context: ctx, Handler: handler}
}

/*Recommend swagger:route GET /recommend Recommend recommend

推荐(备用)

首页推荐

*/
type Recommend struct {
	Context *middleware.Context
	Handler RecommendHandler
}

func (o *Recommend) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRecommendParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
