// Code generated by go-swagger; DO NOT EDIT.

package recommend

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingapi/models"
)

// RecommendOKCode is the HTTP code returned for type RecommendOK
const RecommendOKCode int = 200

/*RecommendOK 登录成功，返回登录信息

swagger:response recommendOK
*/
type RecommendOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20012 `json:"body,omitempty"`
}

// NewRecommendOK creates RecommendOK with default headers values
func NewRecommendOK() *RecommendOK {
	return &RecommendOK{}
}

// WithPayload adds the payload to the recommend o k response
func (o *RecommendOK) WithPayload(payload *models.InlineResponse20012) *RecommendOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the recommend o k response
func (o *RecommendOK) SetPayload(payload *models.InlineResponse20012) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RecommendOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*RecommendDefault error

swagger:response recommendDefault
*/
type RecommendDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRecommendDefault creates RecommendDefault with default headers values
func NewRecommendDefault(code int) *RecommendDefault {
	if code <= 0 {
		code = 500
	}

	return &RecommendDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the recommend default response
func (o *RecommendDefault) WithStatusCode(code int) *RecommendDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the recommend default response
func (o *RecommendDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the recommend default response
func (o *RecommendDefault) WithPayload(payload *models.Error) *RecommendDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the recommend default response
func (o *RecommendDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RecommendDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
