// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Tingting(Api)
Tingting(Api)


    Schemes:
      http
    Host: virtserver.swaggerhub.com
    BasePath: /nanjingyouzi/TingtingApi/1.0.0
    Version: 1.0.0
    Contact: <64060764@qq.com>

    Consumes:
    - application/json
    - multipart/form-data

    Produces:
    - application/json

swagger:meta
*/
package restapi
