// Code generated by go-swagger; DO NOT EDIT.

package banner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrBannerDetailHandlerFunc turns a function with the right signature into a banner detail handler
type NrBannerDetailHandlerFunc func(NrBannerDetailParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrBannerDetailHandlerFunc) Handle(params NrBannerDetailParams) middleware.Responder {
	return fn(params)
}

// NrBannerDetailHandler interface for that can handle valid banner detail params
type NrBannerDetailHandler interface {
	Handle(NrBannerDetailParams) middleware.Responder
}

// NewNrBannerDetail creates a new http.Handler for the banner detail operation
func NewNrBannerDetail(ctx *middleware.Context, handler NrBannerDetailHandler) *NrBannerDetail {
	return &NrBannerDetail{Context: ctx, Handler: handler}
}

/*NrBannerDetail swagger:route GET /banner/detail Banner bannerDetail

Banner详情

Banner详情

*/
type NrBannerDetail struct {
	Context *middleware.Context
	Handler NrBannerDetailHandler
}

func (o *NrBannerDetail) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrBannerDetailParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
