// Code generated by go-swagger; DO NOT EDIT.

package banner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingapi/models"
)

// BannerDetailOKCode is the HTTP code returned for type BannerDetailOK
const BannerDetailOKCode int = 200

/*BannerDetailOK 登录成功，返回登录信息

swagger:response bannerDetailOK
*/
type BannerDetailOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20011 `json:"body,omitempty"`
}

// NewBannerDetailOK creates BannerDetailOK with default headers values
func NewBannerDetailOK() *BannerDetailOK {
	return &BannerDetailOK{}
}

// WithPayload adds the payload to the banner detail o k response
func (o *BannerDetailOK) WithPayload(payload *models.InlineResponse20011) *BannerDetailOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the banner detail o k response
func (o *BannerDetailOK) SetPayload(payload *models.InlineResponse20011) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BannerDetailOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrBannerDetailDefault error

swagger:response bannerDetailDefault
*/
type NrBannerDetailDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrBannerDetailDefault creates NrBannerDetailDefault with default headers values
func NewNrBannerDetailDefault(code int) *NrBannerDetailDefault {
	if code <= 0 {
		code = 500
	}

	return &NrBannerDetailDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the banner detail default response
func (o *NrBannerDetailDefault) WithStatusCode(code int) *NrBannerDetailDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the banner detail default response
func (o *NrBannerDetailDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the banner detail default response
func (o *NrBannerDetailDefault) WithPayload(payload *models.Error) *NrBannerDetailDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the banner detail default response
func (o *NrBannerDetailDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrBannerDetailDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
