// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingapi/models"
)

// AlbumBookListOKCode is the HTTP code returned for type AlbumBookListOK
const AlbumBookListOKCode int = 200

/*AlbumBookListOK 登录成功，返回登录信息

swagger:response albumBookListOK
*/
type AlbumBookListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20019 `json:"body,omitempty"`
}

// NewAlbumBookListOK creates AlbumBookListOK with default headers values
func NewAlbumBookListOK() *AlbumBookListOK {
	return &AlbumBookListOK{}
}

// WithPayload adds the payload to the album book list o k response
func (o *AlbumBookListOK) WithPayload(payload *models.InlineResponse20019) *AlbumBookListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the album book list o k response
func (o *AlbumBookListOK) SetPayload(payload *models.InlineResponse20019) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AlbumBookListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AlbumBookListDefault error

swagger:response albumBookListDefault
*/
type AlbumBookListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAlbumBookListDefault creates AlbumBookListDefault with default headers values
func NewAlbumBookListDefault(code int) *AlbumBookListDefault {
	if code <= 0 {
		code = 500
	}

	return &AlbumBookListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the album book list default response
func (o *AlbumBookListDefault) WithStatusCode(code int) *AlbumBookListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the album book list default response
func (o *AlbumBookListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the album book list default response
func (o *AlbumBookListDefault) WithPayload(payload *models.Error) *AlbumBookListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the album book list default response
func (o *AlbumBookListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AlbumBookListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
