// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// BookListFavHandlerFunc turns a function with the right signature into a book list fav handler
type BookListFavHandlerFunc func(BookListFavParams) middleware.Responder

// Handle executing the request and returning a response
func (fn BookListFavHandlerFunc) Handle(params BookListFavParams) middleware.Responder {
	return fn(params)
}

// BookListFavHandler interface for that can handle valid book list fav params
type BookListFavHandler interface {
	Handle(BookListFavParams) middleware.Responder
}

// NewBookListFav creates a new http.Handler for the book list fav operation
func NewBookListFav(ctx *middleware.Context, handler BookListFavHandler) *BookListFav {
	return &BookListFav{Context: ctx, Handler: handler}
}

/*BookListFav swagger:route GET /book/list/fav Book bookListFav

根据用户收藏书本

根据用户收藏书本

*/
type BookListFav struct {
	Context *middleware.Context
	Handler BookListFavHandler
}

func (o *BookListFav) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewBookListFavParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
