// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingapi/models"
)

// BookBuyOKCode is the HTTP code returned for type BookBuyOK
const BookBuyOKCode int = 200

/*BookBuyOK 购买专辑返回结果

swagger:response bookBuyOK
*/
type BookBuyOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2003 `json:"body,omitempty"`
}

// NewBookBuyOK creates BookBuyOK with default headers values
func NewBookBuyOK() *BookBuyOK {
	return &BookBuyOK{}
}

// WithPayload adds the payload to the book buy o k response
func (o *BookBuyOK) WithPayload(payload *models.InlineResponse2003) *BookBuyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book buy o k response
func (o *BookBuyOK) SetPayload(payload *models.InlineResponse2003) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookBuyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*BookBuyDefault error

swagger:response bookBuyDefault
*/
type BookBuyDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBookBuyDefault creates BookBuyDefault with default headers values
func NewBookBuyDefault(code int) *BookBuyDefault {
	if code <= 0 {
		code = 500
	}

	return &BookBuyDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the book buy default response
func (o *BookBuyDefault) WithStatusCode(code int) *BookBuyDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the book buy default response
func (o *BookBuyDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the book buy default response
func (o *BookBuyDefault) WithPayload(payload *models.Error) *BookBuyDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book buy default response
func (o *BookBuyDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookBuyDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
