// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingapi/models"
)

// BookListFavOKCode is the HTTP code returned for type BookListFavOK
const BookListFavOKCode int = 200

/*BookListFavOK 根据用户收藏书本

swagger:response bookListFavOK
*/
type BookListFavOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2004 `json:"body,omitempty"`
}

// NewBookListFavOK creates BookListFavOK with default headers values
func NewBookListFavOK() *BookListFavOK {
	return &BookListFavOK{}
}

// WithPayload adds the payload to the book list fav o k response
func (o *BookListFavOK) WithPayload(payload *models.InlineResponse2004) *BookListFavOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book list fav o k response
func (o *BookListFavOK) SetPayload(payload *models.InlineResponse2004) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookListFavOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*BookListFavDefault error

swagger:response bookListFavDefault
*/
type BookListFavDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBookListFavDefault creates BookListFavDefault with default headers values
func NewBookListFavDefault(code int) *BookListFavDefault {
	if code <= 0 {
		code = 500
	}

	return &BookListFavDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the book list fav default response
func (o *BookListFavDefault) WithStatusCode(code int) *BookListFavDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the book list fav default response
func (o *BookListFavDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the book list fav default response
func (o *BookListFavDefault) WithPayload(payload *models.Error) *BookListFavDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book list fav default response
func (o *BookListFavDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookListFavDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
