// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingapi/models"
)

// BookChapListOKCode is the HTTP code returned for type BookChapListOK
const BookChapListOKCode int = 200

/*BookChapListOK 登录成功，返回登录信息

swagger:response bookChapListOK
*/
type BookChapListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20018 `json:"body,omitempty"`
}

// NewBookChapListOK creates BookChapListOK with default headers values
func NewBookChapListOK() *BookChapListOK {
	return &BookChapListOK{}
}

// WithPayload adds the payload to the book chap list o k response
func (o *BookChapListOK) WithPayload(payload *models.InlineResponse20018) *BookChapListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book chap list o k response
func (o *BookChapListOK) SetPayload(payload *models.InlineResponse20018) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookChapListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*BookChapListDefault error

swagger:response bookChapListDefault
*/
type BookChapListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBookChapListDefault creates BookChapListDefault with default headers values
func NewBookChapListDefault(code int) *BookChapListDefault {
	if code <= 0 {
		code = 500
	}

	return &BookChapListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the book chap list default response
func (o *BookChapListDefault) WithStatusCode(code int) *BookChapListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the book chap list default response
func (o *BookChapListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the book chap list default response
func (o *BookChapListDefault) WithPayload(payload *models.Error) *BookChapListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book chap list default response
func (o *BookChapListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookChapListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
