// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingapi/models"
)

// BookDefaultOKCode is the HTTP code returned for type BookDefaultOK
const BookDefaultOKCode int = 200

/*BookDefaultOK 登录成功，返回登录信息

swagger:response bookDefaultOK
*/
type BookDefaultOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20077 `json:"body,omitempty"`
}

// NewBookDefaultOK creates BookDefaultOK with default headers values
func NewBookDefaultOK() *BookDefaultOK {
	return &BookDefaultOK{}
}

// WithPayload adds the payload to the book default o k response
func (o *BookDefaultOK) WithPayload(payload *models.InlineResponse20077) *BookDefaultOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book default o k response
func (o *BookDefaultOK) SetPayload(payload *models.InlineResponse20077) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookDefaultOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*BookDefaultDefault error

swagger:response bookDefaultDefault
*/
type BookDefaultDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewBookDefaultDefault creates BookDefaultDefault with default headers values
func NewBookDefaultDefault(code int) *BookDefaultDefault {
	if code <= 0 {
		code = 500
	}

	return &BookDefaultDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the book default default response
func (o *BookDefaultDefault) WithStatusCode(code int) *BookDefaultDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the book default default response
func (o *BookDefaultDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the book default default response
func (o *BookDefaultDefault) WithPayload(payload *models.Error) *BookDefaultDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the book default default response
func (o *BookDefaultDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BookDefaultDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
