// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// BookBuyHandlerFunc turns a function with the right signature into a book buy handler
type BookBuyHandlerFunc func(BookBuyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn BookBuyHandlerFunc) Handle(params BookBuyParams) middleware.Responder {
	return fn(params)
}

// BookBuyHandler interface for that can handle valid book buy params
type BookBuyHandler interface {
	Handle(BookBuyParams) middleware.Responder
}

// NewBookBuy creates a new http.Handler for the book buy operation
func NewBookBuy(ctx *middleware.Context, handler BookBuyHandler) *BookBuy {
	return &BookBuy{Context: ctx, Handler: handler}
}

/*BookBuy swagger:route GET /book/buy Book bookBuy

购买书本

购买书本

*/
type BookBuy struct {
	Context *middleware.Context
	Handler BookBuyHandler
}

func (o *BookBuy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewBookBuyParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
