// Code generated by go-swagger; DO NOT EDIT.

package book

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrBookFavHandlerFunc turns a function with the right signature into a book fav handler
type NrBookFavHandlerFunc func(NrBookFavParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrBookFavHandlerFunc) Handle(params NrBookFavParams) middleware.Responder {
	return fn(params)
}

// NrBookFavHandler interface for that can handle valid book fav params
type NrBookFavHandler interface {
	Handle(NrBookFavParams) middleware.Responder
}

// NewNrBookFav creates a new http.Handler for the book fav operation
func NewNrBookFav(ctx *middleware.Context, handler NrBookFavHandler) *NrBookFav {
	return &NrBookFav{Context: ctx, Handler: handler}
}

/*NrBookFav swagger:route GET /book/fav Book bookFav

收藏/取消收藏 书本

收藏/取消收藏 书本

*/
type NrBookFav struct {
	Context *middleware.Context
	Handler NrBookFavHandler
}

func (o *NrBookFav) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrBookFavParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
