// Code generated by go-swagger; DO NOT EDIT.

package icon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingapi/models"
)

// IconListOKCode is the HTTP code returned for type IconListOK
const IconListOKCode int = 200

/*IconListOK 登录成功，返回登录信息

swagger:response iconListOK
*/
type IconListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2002 `json:"body,omitempty"`
}

// NewIconListOK creates IconListOK with default headers values
func NewIconListOK() *IconListOK {
	return &IconListOK{}
}

// WithPayload adds the payload to the icon list o k response
func (o *IconListOK) WithPayload(payload *models.InlineResponse2002) *IconListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the icon list o k response
func (o *IconListOK) SetPayload(payload *models.InlineResponse2002) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *IconListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrIconListDefault error

swagger:response iconListDefault
*/
type NrIconListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrIconListDefault creates NrIconListDefault with default headers values
func NewNrIconListDefault(code int) *NrIconListDefault {
	if code <= 0 {
		code = 500
	}

	return &NrIconListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the icon list default response
func (o *NrIconListDefault) WithStatusCode(code int) *NrIconListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the icon list default response
func (o *NrIconListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the icon list default response
func (o *NrIconListDefault) WithPayload(payload *models.Error) *NrIconListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the icon list default response
func (o *NrIconListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrIconListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
