// Code generated by go-swagger; DO NOT EDIT.

package icon

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// NrIconListHandlerFunc turns a function with the right signature into a icon list handler
type NrIconListHandlerFunc func(NrIconListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrIconListHandlerFunc) Handle(params NrIconListParams) middleware.Responder {
	return fn(params)
}

// NrIconListHandler interface for that can handle valid icon list params
type NrIconListHandler interface {
	Handle(NrIconListParams) middleware.Responder
}

// NewNrIconList creates a new http.Handler for the icon list operation
func NewNrIconList(ctx *middleware.Context, handler NrIconListHandler) *NrIconList {
	return &NrIconList{Context: ctx, Handler: handler}
}

/*NrIconList swagger:route GET /icon/list Icon iconList

app中间图标列表

app中间图标列表

*/
type NrIconList struct {
	Context *middleware.Context
	Handler NrIconListHandler
}

func (o *NrIconList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrIconListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
