// Code generated by go-swagger; DO NOT EDIT.

package album

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// AlbumBuyHandlerFunc turns a function with the right signature into a album buy handler
type AlbumBuyHandlerFunc func(AlbumBuyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AlbumBuyHandlerFunc) Handle(params AlbumBuyParams) middleware.Responder {
	return fn(params)
}

// AlbumBuyHandler interface for that can handle valid album buy params
type AlbumBuyHandler interface {
	Handle(AlbumBuyParams) middleware.Responder
}

// NewAlbumBuy creates a new http.Handler for the album buy operation
func NewAlbumBuy(ctx *middleware.Context, handler AlbumBuyHandler) *AlbumBuy {
	return &AlbumBuy{Context: ctx, Handler: handler}
}

/*AlbumBuy swagger:route GET /album/buy Album albumBuy

购买专辑

购买专辑

*/
type AlbumBuy struct {
	Context *middleware.Context
	Handler AlbumBuyHandler
}

func (o *AlbumBuy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAlbumBuyParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
