// Code generated by go-swagger; DO NOT EDIT.

package album

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingapi/models"
)

// AlbumListFavOKCode is the HTTP code returned for type AlbumListFavOK
const AlbumListFavOKCode int = 200

/*AlbumListFavOK 根据用户信息获取收藏专辑

swagger:response albumListFavOK
*/
type AlbumListFavOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2006 `json:"body,omitempty"`
}

// NewAlbumListFavOK creates AlbumListFavOK with default headers values
func NewAlbumListFavOK() *AlbumListFavOK {
	return &AlbumListFavOK{}
}

// WithPayload adds the payload to the album list fav o k response
func (o *AlbumListFavOK) WithPayload(payload *models.InlineResponse2006) *AlbumListFavOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the album list fav o k response
func (o *AlbumListFavOK) SetPayload(payload *models.InlineResponse2006) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AlbumListFavOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*AlbumListFavDefault error

swagger:response albumListFavDefault
*/
type AlbumListFavDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAlbumListFavDefault creates AlbumListFavDefault with default headers values
func NewAlbumListFavDefault(code int) *AlbumListFavDefault {
	if code <= 0 {
		code = 500
	}

	return &AlbumListFavDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the album list fav default response
func (o *AlbumListFavDefault) WithStatusCode(code int) *AlbumListFavDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the album list fav default response
func (o *AlbumListFavDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the album list fav default response
func (o *AlbumListFavDefault) WithPayload(payload *models.Error) *AlbumListFavDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the album list fav default response
func (o *AlbumListFavDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AlbumListFavDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
