// Code generated by go-swagger; DO NOT EDIT.

package album

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingapi/models"
)

// AlbumFavOKCode is the HTTP code returned for type AlbumFavOK
const AlbumFavOKCode int = 200

/*AlbumFavOK 购买专辑返回结果

swagger:response albumFavOK
*/
type AlbumFavOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse2007 `json:"body,omitempty"`
}

// NewAlbumFavOK creates AlbumFavOK with default headers values
func NewAlbumFavOK() *AlbumFavOK {
	return &AlbumFavOK{}
}

// WithPayload adds the payload to the album fav o k response
func (o *AlbumFavOK) WithPayload(payload *models.InlineResponse2007) *AlbumFavOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the album fav o k response
func (o *AlbumFavOK) SetPayload(payload *models.InlineResponse2007) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AlbumFavOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrAlbumFavDefault error

swagger:response albumFavDefault
*/
type NrAlbumFavDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrAlbumFavDefault creates NrAlbumFavDefault with default headers values
func NewNrAlbumFavDefault(code int) *NrAlbumFavDefault {
	if code <= 0 {
		code = 500
	}

	return &NrAlbumFavDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the album fav default response
func (o *NrAlbumFavDefault) WithStatusCode(code int) *NrAlbumFavDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the album fav default response
func (o *NrAlbumFavDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the album fav default response
func (o *NrAlbumFavDefault) WithPayload(payload *models.Error) *NrAlbumFavDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the album fav default response
func (o *NrAlbumFavDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrAlbumFavDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
