// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingapi/models"
)

// MsgListOKCode is the HTTP code returned for type MsgListOK
const MsgListOKCode int = 200

/*MsgListOK 登录成功，返回登录信息

swagger:response msgListOK
*/
type MsgListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20013 `json:"body,omitempty"`
}

// NewMsgListOK creates MsgListOK with default headers values
func NewMsgListOK() *MsgListOK {
	return &MsgListOK{}
}

// WithPayload adds the payload to the msg list o k response
func (o *MsgListOK) WithPayload(payload *models.InlineResponse20013) *MsgListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the msg list o k response
func (o *MsgListOK) SetPayload(payload *models.InlineResponse20013) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MsgListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*MsgListDefault error

swagger:response msgListDefault
*/
type MsgListDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMsgListDefault creates MsgListDefault with default headers values
func NewMsgListDefault(code int) *MsgListDefault {
	if code <= 0 {
		code = 500
	}

	return &MsgListDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the msg list default response
func (o *MsgListDefault) WithStatusCode(code int) *MsgListDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the msg list default response
func (o *MsgListDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the msg list default response
func (o *MsgListDefault) WithPayload(payload *models.Error) *MsgListDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the msg list default response
func (o *MsgListDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MsgListDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
