// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingapi/models"
)

// MemberInitOKCode is the HTTP code returned for type MemberInitOK
const MemberInitOKCode int = 200

/*MemberInitOK search results matching criteria

swagger:response memberInitOK
*/
type MemberInitOK struct {

	/*
	  In: Body
	*/
	Payload *models.InitModel `json:"body,omitempty"`
}

// NewMemberInitOK creates MemberInitOK with default headers values
func NewMemberInitOK() *MemberInitOK {
	return &MemberInitOK{}
}

// WithPayload adds the payload to the member init o k response
func (o *MemberInitOK) WithPayload(payload *models.InitModel) *MemberInitOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the member init o k response
func (o *MemberInitOK) SetPayload(payload *models.InitModel) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MemberInitOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*NrMemberInitDefault error

swagger:response memberInitDefault
*/
type NrMemberInitDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNrMemberInitDefault creates NrMemberInitDefault with default headers values
func NewNrMemberInitDefault(code int) *NrMemberInitDefault {
	if code <= 0 {
		code = 500
	}

	return &NrMemberInitDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the member init default response
func (o *NrMemberInitDefault) WithStatusCode(code int) *NrMemberInitDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the member init default response
func (o *NrMemberInitDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the member init default response
func (o *NrMemberInitDefault) WithPayload(payload *models.Error) *NrMemberInitDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the member init default response
func (o *NrMemberInitDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NrMemberInitDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
