// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	_"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	middleware "github.com/go-openapi/runtime/middleware"
	"tingtingapi/models"
	"fmt"
	"tingtingbackend/var"
)

// NrMemberCheckRechargeHandlerFunc turns a function with the right signature into a member check recharge handler
type NrMemberCheckRechargeHandlerFunc func(NrMemberCheckRechargeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn NrMemberCheckRechargeHandlerFunc) Handle(params NrMemberCheckRechargeParams) middleware.Responder {
	return fn(params)
}

// NrMemberCheckRechargeHandler interface for that can handle valid member check recharge params
type NrMemberCheckRechargeHandler interface {
	Handle(NrMemberCheckRechargeParams) middleware.Responder
}

// NewNrMemberCheckRecharge creates a new http.Handler for the member check recharge operation
func NewNrMemberCheckRecharge(ctx *middleware.Context, handler NrMemberCheckRechargeHandler) *NrMemberCheckRecharge {
	return &NrMemberCheckRecharge{Context: ctx, Handler: handler}
}

/*NrMemberCheckRecharge swagger:route GET /member/checkRecharge Member memberCheckRecharge

检查是否充值成功

检查是否充值成功

*/
type NrMemberCheckRecharge struct {
	Context *middleware.Context
	Handler NrMemberCheckRechargeHandler
}

func (o *NrMemberCheckRecharge) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNrMemberCheckRechargeParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	var ok MemberCheckRechargeOK
	var response models.InlineResponse2002
	var status models.Response

	db,err := _var.OpenConnection()
	if err!=nil{
		fmt.Println(err.Error())
	}

	var recharge models.RechargeModel

	fmt.Println("sn=",*(Params.SerialNumber))
	fmt.Println("md=",*(Params.MemberID))
	db.Table("recharge").Select([]string{"id","memberId","type","order_no","status","value"}).Where("order_no=?",Params.SerialNumber).Where("memberId=?",Params.MemberID).Last(&recharge)
	fmt.Println(recharge)
	if(recharge.ID==0) {
		status.UnmarshalBinary([]byte(_var.Response200(201,"没找到对应流水号")))
		//response.SerialNumber = "-1"
	}else{
		status.UnmarshalBinary([]byte(_var.Response200(200,"找到对应流水号")))
		//response.SerialNumber = recharge.Order_no
	}

	response.Status = &status
	ok.SetPayload(&response)
	o.Context.Respond(rw, r, route.Produces, route, ok)

}
