// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	_"github.com/jinzhu/gorm"
	_ "github.com/jinzhu/gorm/dialects/mysql"
	middleware "github.com/go-openapi/runtime/middleware"
	"tingtingapi/models"
	"fmt"
	"tingtingbackend/var"
)

// RecordListHandlerFunc turns a function with the right signature into a record list handler
type RecordListHandlerFunc func(RecordListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RecordListHandlerFunc) Handle(params RecordListParams) middleware.Responder {
	return fn(params)
}

// RecordListHandler interface for that can handle valid record list params
type RecordListHandler interface {
	Handle(RecordListParams) middleware.Responder
}

// NewRecordList creates a new http.Handler for the record list operation
func NewRecordList(ctx *middleware.Context, handler RecordListHandler) *RecordList {
	return &RecordList{Context: ctx, Handler: handler}
}

/*RecordList swagger:route GET /member/record/list Member recordList

获取录音列表

获取录音列表

*/
type RecordList struct {
	Context *middleware.Context
	Handler RecordListHandler
}

func (o *RecordList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRecordListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	var ok RecordListOK
	var response models.InlineResponse20014
	var recordList models.InlineResponse20014RecordList

	db,err := _var.OpenConnection()
	if err!=nil{
		fmt.Println(err.Error())
	}
	defer db.Close()
	db.Table("records").Where(map[string]interface{}{"status":0}).Where("user_id=?",Params.MemberID).Find(&recordList)
	//query

	//data

	response.RecordList = recordList

	//status
	var status models.Response
	status.UnmarshalBinary([]byte(_var.Response200(200,"ok")))
	response.Status = &status

	ok.SetPayload(&response)

	o.Context.Respond(rw, r, route.Produces, route, ok)

}
