// Code generated by go-swagger; DO NOT EDIT.

package member

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// RecordListHandlerFunc turns a function with the right signature into a record list handler
type RecordListHandlerFunc func(RecordListParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RecordListHandlerFunc) Handle(params RecordListParams) middleware.Responder {
	return fn(params)
}

// RecordListHandler interface for that can handle valid record list params
type RecordListHandler interface {
	Handle(RecordListParams) middleware.Responder
}

// NewRecordList creates a new http.Handler for the record list operation
func NewRecordList(ctx *middleware.Context, handler RecordListHandler) *RecordList {
	return &RecordList{Context: ctx, Handler: handler}
}

/*RecordList swagger:route GET /member/record/list Member recordList

获取录音列表

获取录音列表

*/
type RecordList struct {
	Context *middleware.Context
	Handler RecordListHandler
}

func (o *RecordList) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRecordListParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
