// Code generated by go-swagger; DO NOT EDIT.

package category

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "tingtingapi/models"
)

// CategorySubListOKCode is the HTTP code returned for type CategorySubListOK
const CategorySubListOKCode int = 200

/*CategorySubListOK 查询成功，返回组织机构列表信息

swagger:response categorySubListOK
*/
type CategorySubListOK struct {

	/*
	  In: Body
	*/
	Payload *models.InlineResponse20023 `json:"body,omitempty"`
}

// NewCategorySubListOK creates CategorySubListOK with default headers values
func NewCategorySubListOK() *CategorySubListOK {
	return &CategorySubListOK{}
}

// WithPayload adds the payload to the category sub list o k response
func (o *CategorySubListOK) WithPayload(payload *models.InlineResponse20023) *CategorySubListOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the category sub list o k response
func (o *CategorySubListOK) SetPayload(payload *models.InlineResponse20023) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CategorySubListOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
