// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Album album
// swagger:model Album
type Album struct {

	// album Id
	AlbumID int64 `json:"albumId,omitempty"`

	// album name
	AlbumName string `json:"albumName,omitempty"`

	// album Id
	ID int64 `json:"id,omitempty"`

	// album name
	Name string `json:"name,omitempty"`

	Value int64 `json:"value,omitempty"`

	Icon string `json:"icon,omitempty"`

	Cover string `json:"cover,omitempty"`
}

// Validate validates this album
func (m *Album) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Album) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Album) UnmarshalBinary(b []byte) error {
	var res Album
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
