// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Album album
// swagger:model Album
type Album struct {

	// album Id
	AlbumID int64 `json:"albumId"`

	// album name
	AlbumName string `json:"albumName"`

	Sub_Title string `json:"sub_title"`

	Time int64 `json:"time"`

	// album Id
	ID int64 `json:"id"`

	// album name
	Name string `json:"name"`

	Value int64 `json:"value"`

	Icon string `json:"icon"`

	Cover string `json:"cover"`

	Play_Count int64 `json:"playCount"`

	Author_Name string `json:"author_name"`

	Author_Avatar string `json:"author_avatar"`

	Books_Number int64 `json:"books_number"`

	Summary string `json:"summary"`

}

// Validate validates this album
func (m *Album) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Album) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Album) UnmarshalBinary(b []byte) error {
	var res Album
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
