// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Book book
// swagger:model Book
type Book struct {

	// author avatar
	AuthorAvatar string `json:"authorAvatar"`

	// author name
	AuthorName string `json:"authorName"`

	// book Id
	BookID int64 `json:"bookId"`

	// clips number
	ClipsNumber int64 `json:"clipsNumber"`

	// icon
	Icon string `json:"icon"`

	// name
	Name string `json:"name"`

	// play count
	PlayCount int64 `json:"playCount"`

	// show icon
	ShowIcon bool `json:"showIcon"`

	// sub category Id
	SubCategoryID int64 `json:"subCategoryId"`

	// sub title
	SubTitle string `json:"subTitle"`

	// summary
	Summary string `json:"summary"`

	StartTime string `json:"startTime"`

	Fav bool `json:"fav"`
}

// Validate validates this book
func (m *Book) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Book) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Book) UnmarshalBinary(b []byte) error {
	var res Book
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
