// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Chapter chapter
// swagger:model Chapter
type Chapter struct {

	Id int64 `json:"id"`
	// big cover
	BigCover string `json:"bigCover"`

	// duration
	Duration int64 `json:"duration"`

	// hls Url
	HlsURL string `json:"hlsUrl"`

	// icon
	Icon string `json:"icon"`

	// mp3 Url
	Mp3URL string `json:"mp3Url"`

	// name
	Name string `json:"name"`

	// order
	Order int64 `json:"order"`

	// play count
	PlayCount int64 `json:"playCount"`

	// show icon
	ShowIcon bool `json:"showIcon"`

	// sub title
	SubTitle string `json:"subTitle"`

	// summary
	Summary string `json:"summary"`

	// update tips
	UpdateTips string `json:"updateTips"`
}

// Validate validates this chapter
func (m *Chapter) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Chapter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Chapter) UnmarshalBinary(b []byte) error {
	var res Chapter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
