// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InlineResponse20010 inline response 200 10
// swagger:model inline_response_200_10
type InlineResponse20010 struct {

	// album list
	AlbumList InlineResponse20010AlbumList `json:"albumList"`

	// book list
	BookList InlineResponse20010BookList `json:"bookList"`

	// chapter list
	ChapterList InlineResponse20010ChapterList `json:"chapterList"`

	// record list
	RecordList InlineResponse20010RecordList `json:"recordList"`

	// status
	Status *Response `json:"status,omitempty"`
}

// Validate validates this inline response 200 10
func (m *InlineResponse20010) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InlineResponse20010) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if m.Status != nil {

		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InlineResponse20010) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InlineResponse20010) UnmarshalBinary(b []byte) error {
	var res InlineResponse20010
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
