// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (

)

// Icon icon
// swagger:model Icon
type Member struct {
	ID int64 `json:"id"`
	// cover
	Area string `json:"area"`

	// icon
	Avatar string `json:"avatar"`

	// id
	Gender int64 `json:"gender"`

	// name
	Grade string `json:"grade"`

	// order
	Level int64 `json:"level"`

	Name string `json:"name"`

	Phone string `json:"phone"`

	Tags string `json:"tags"`

	// web Url
	Password string `json:"password"`

	Money int64 `json:"money"`

	Ts  int64 `json:"ts"`

	Status  int64 `json:"status"`

	Ts1  string `json:"ts1"`

	Birth string `json:"birth"`

	BuyedAlbumsCount int64 `json:"buyedAlbumsCount"`


}

