// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (

)

// Icon icon
// swagger:model Icon
type Member struct {
	ID int64 `json:"id,omitempty"`
	// cover
	Area string `json:"area,omitempty"`

	// icon
	Avatar string `json:"avatar,omitempty"`

	// id
	Gender int64 `json:"gender,omitempty"`

	// name
	Grade string `json:"grade,omitempty"`

	// order
	Level int64 `json:"level,omitempty"`

	Name string `json:"name,omitempty"`

	Phone string `json:"phone,omitempty"`

	Tags string `json:"tags,omitempty"`

	// web Url
	Password string `json:"password,omitempty"`
}

