// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (

)

// Msg msg
// swagger:model Msg
type Msg struct {

	// create time
	Create_Time int64 `json:"create_time"`

	// from
	From string `json:"from,omitempty"`

	// sub title
	SubTitle string `json:"sub_title"`

	// title
	Title string `json:"title"`

	Id  int64 `json:"id"`
}

// Validate validates this msg
/*
func (m *Msg) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Msg) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Msg) UnmarshalBinary(b []byte) error {
	var res Msg
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
*/
