// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Recharge 充值结果
// swagger:model Recharge
type RechargeModel struct {

	ID int64 `json:"id,omitempty"`
	// 0=等待 1=成功 2=失败 3=其他
	MemberId int64 `json:"memberId,omitempty"`

	// msg
	Type string `json:"type,omitempty"`

	// 支付平台产生的流水号
	Order_no string `json:"order_no,omitempty"`

	Status int64 `json:"status,omitempty"`

	Value float64 `json:"value,omitempty"`
}

// Validate validates this login ret
func (m *RechargeModel) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *RechargeModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RechargeModel) UnmarshalBinary(b []byte) error {
	var res RechargeModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
