// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Record record
// swagger:model Record
type Record struct {

	// cover
	Cover string `json:"cover,omitempty"`

	// duration
	Duration int64 `json:"duration,omitempty"`

	// play count
	PlayCount int64 `json:"playCount,omitempty"`

	// sub title
	Sub_Title string `json:"subTitle,omitempty"`

	// summary
	Summary string `json:"summary,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// url
	URL string `json:"url,omitempty"`

	User_id  int64 `json:"user_id,omitempty"`

	Icon  string `json:"icon,omitempty"`

}

// Validate validates this record
func (m *Record) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Record) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Record) UnmarshalBinary(b []byte) error {
	var res Record
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
