// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Record record
// swagger:model Record
type Record struct {

	// cover
	Cover string `json:"cover"`

	// duration
	Duration int64 `json:"duration"`

	// play count
	PlayCount int64 `json:"playCount"`

	// sub title
	Sub_Title string `json:"subTitle"`

	// summary
	Summary string `json:"summary"`

	// title
	Title string `json:"title"`

	// url
	URL string `json:"url"`

	User_id  int64 `json:"user_id"`

	Icon  string `json:"icon"`

	Time int64 `json:"time"`

}

// Validate validates this record
func (m *Record) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Record) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Record) UnmarshalBinary(b []byte) error {
	var res Record
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
