// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (

)

// Icon icon
// swagger:model Icon
type Scan struct {
	ID int64 `json:"id,omitempty"`
	// cover
	ScanId string `json:"scanId,omitempty"`

	// icon
	BookId int64 `json:"bookId,omitempty"`

	// id
	Status int64 `json:"status,omitempty"`

}

